name: Python Application for testing


on: [push]

jobs:
  build:

    runs-on: ubuntu
    steps:
    - uses: actions/checkout@v2
    - name: Set up Pyton 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Linting
      run: |
        make lint
    - name: Testing with Pytest
      run: |
        make test
    - name: Code formatting
      run: |
        make format
    
